### ISSUE TITLE
Transferring Grasp from one to anotehr gripper

### ISSUE THREAD

**Issue by JeonHoKang** [IRVLUTD/isaac_sim_grasping#4]
Hello, I hope you are doing well.

I am currently trying to implement my grasp with robotiq 2f gripper with my own CAD file.

I am facing many issues but particularly generating grasps with robotiq gripper with graspit is particularly challenging.

I was wondering if there is any way that we can transfer grasp from another gripper like fetch to work on robotiq 2f gripper?

I saw transfer.py code but did not seem to directly convert the grasps from one gripper to another as I suspected.

Thank you very much for your help.

**Comment by FelipeCasas** [comment]
Hello, 

Yes, our transfer_st.py uses already transferred grasps to run the simulation. We decided to do so since transferring the poses while running the simulation generated too much overhead. You can find the reference poses we used to transfer the grasps from one gripper to another within the helpful scripts of the clean branch. There is also a jupyter notebook in where you can see an example of how we transferred the grasp poses. 
https://github.com/IRVLUTD/isaac_sim_grasping/tree/d3a192e304ee7cdbeebd3c3ba1869e2d9cf5e057/helpful_scripts. 

I hope this helps!

**Comment by FelipeCasas** [comment]
The branch will be merged as soon as the documentation is updated and we ensure the standalones are error free.

**Comment by JeonHoKang** [comment]
Thank you so much for your response. I really want to implement this system and I tried generating graspit sampled grasps with different grippers but they all face away from the object. Is there any conversion. Of the reference frame that you did to make it work with isaac sim?

**Comment by FelipeCasas** [comment]
Hello, 

Did you load the grasps using Isaac Sim? There are a couple of things to keep in mind: Isaac Sim uses a quaternion notation of wxyz and the poses we use on our dataset are poses of the gripper with respect to the object. If we go into the details, the simulation inverts the quaternion in order to place the object in the right position. 

I am tagging @kninad to the conversation. 

I hope this helps!

**Comment by kninad** [comment]
There are a couple of differences which I can I think of:
- When generating data with Graspit, the default convention for pose is (position, quat_xyzw).
- Isaac sim expects the quaternion to be in quat_wxyz format.
- So make sure that this is followed before visualzing in isaac sim...
- another simple check to visualize is to use pybullet (which uses quat_xyzw) format -- so graspit data can directly be used there.

**Comment by kninad** [comment]
Generating grasps with graspit on robotiq-2F seems a bit challenging iirc due to it's mimic joint property. I recall seeing some open issues on graspit's github repository.
