### ISSUE TITLE
Error when running Allegro Hand

### ISSUE THREAD

**Issue by chaiban** [IRVLUTD/isaac_sim_grasping#7]
Hi, Thank you for great work.

Error in Function::Function for 'link_tf_link_0.0' [SXFunction] at .../casadi/core/function.cpp:240:
.../casadi/core/function_internal.cpp:68: Function name is not valid. A valid function name is a std::string starting with a letter followed by letters, numbers or non-consecutive underscores. It may also not match the keywords 'null', 'jac' or 'hess'. Got 'link_tf_link_0.0' 

I am facing this error when i run this for allegro hand. Remaining hands works well. Could you please let me know if you changed something for allegro hand? 

I am using optas for visualization.

Thank you!

**Comment by kninad** [comment]
For optas/casadi visualization, the error for Allegro is due to some of its links being named as `link_X.0` (X=0,1,2...). The issue is fixed if we:

- replace the `.` to some other char like `_` in the URDF
- replace the mesh file names to reflect this change
- I have attached a zip for this modification: [Allegro_casadi.zip](https://github.com/user-attachments/files/16530116/Allegro_casadi.zip)
